<?php return array (
  'site_title' => 'Gamers Arena',
  'base_color' => '#ff5400',
  'base_secondary' => '#ff7843',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'gameshop',
  'fraction_number' => 2,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'push_notification' => 1,
  'error_log' => 0,
  'strong_password' => 0,
  'registration' => 1,
  'address_verification' => 0,
  'identity_verification' => 0,
  'maintenance' => 1,
  'is_active_cron_notification' => 0,
  'payment_expired' => 15,
  'payment_released' => 7,
  'top_up' => 1,
  'voucher' => 1,
  'gift_card' => 1,
  'sell_post' => 1,
  'sender_email' => 'support@domain.com',
  'sender_email_name' => 'Gamers Arena',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp.mailtrap.io',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'b75b1a5bfa5d58',
    'smtp_password' => 'f89fbe0495a7fc',
  ),
);