<?php

return [
    'Dirty Stapler Extra',
    'Silent Tennis Dash',
    'Nerf Bazooka Phonics',
    'Codename and Remorse',
    'Silent Sumo Invasion',
    'Crimson Cell',
    "Pachinko of Doom",
    "Battle and Words",
    "Fluffy WWE Warrior",
    "Rule of Retribution",
    "Alien Theft",
    "Rise of Power",
    "True Crime: Universe",
    "Bionic Crossdressing",
    "Cool Ninja Kingdom",
    "Dark Mercenary",
    "Star Asylum",
    "Carnival Shack",
    "Day of the Cricket",
    "The Great Werewolf DS",
    "Solar Guardians",
    "Treasures and Epoch",
    "Summer Spelling Returns",
    "Remorse and Revival",
    "Kinky Mahjong X",
    "Remote Spider Kid",
    "Endorspace",
    "Royal Dodgeball",
    "Thunder and Graves",
    "Zamboni in the Outback",
    "Deadstorm",
    "Skydiving Insanity",
    "Archechase",
    "Blasterline",
    "Demon Freedom",
    "Bionic Alert",
    "Spirit Kingdom",
    "Secret Mercenary",
    "Dark Breakout",
    "Strike of Retribution",
    "Vengeance of Duplicity",
    "Deadland",
    "Cantankerous WWII 2K",
    "Chase of Campaigns",
    "NASCAR Diesel",
    "Obscure Age",
    "Evil Legend",
    "Saint Siren",
    "8-Bit Sailor Thieves",
    "Rescue of Betrayal",
];
