<?php

return [
    "Home",
    "About Us",
    "Dashboard",
    "My Profile",
    "2FA Security",
    "Support Ticket",
    "Sign out",
    "Top Up",
    "Voucher",
    "Gift Card",
    "Contact",
    "Sign In",
    "Sign Up",
    "History",
    "Payment",
    "Transaction",
    "Shop more",
    "featured",
    "GAMES VOUCHER",
    "BUY GIFT CARDS",
    "Admin",
    "sign in",
    "Please sign-in to your account and start the adventure",
    "Your Email or Username",
    "name@example.com",
    "Your password",
    "Forgot Password",
    "Remember me",
    "Don't have any account",
    "Register",
    "sign up",
    "First name",
    "John",
    "Last name",
    "Doe",
    "Username",
    "username",
    "Your Email",
    "Your Phone Number",
    "Confirm password",
    "Login",
    "Email Verify",
    "Verify Your Email Address",
    "A fresh verification link has been sent to your email address",
    "Before proceeding, please check your email for a verification link",
    "click here to request another",
    "2FA CODE",
    "Code",
    "Submit",
    "Email Verification",
    "Resend Code",
    "SMS Verification",
    "Didn\'t get Code? Click to",
    "Please confirm your password before continuing",
    "Forgot Your Password",
    "Reset Password",
    "Your Email Address",
    "Enter your Email Address",
    "send password reset link",
    "New Password",
    "Change Password",
    "My Order",
    "Top Up Orders",
    "Search for Transaction ID",
    "Search",
    "No.",
    "TRX",
    "Category",
    "Service",
    "Price",
    "Status",
    "Date - Time",
    "No Data Found",
    "Voucher Orders",
    "More",
    "Voucher Code",
    "Close",
    "Gift Card Orders",
    "Gift Card Code",
    "Remarks",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Time",
    "Fund History",
    "Type Here",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Gateway",
    "Charge",
    "Profile Settings",
    "Joined At",
    "Image Update",
    "Profile Information",
    "Password Setting",
    "Email Address",
    "Phone Number",
    "Preferred language",
    "Select Language",
    "Address",
    "Update User",
    "Current Password",
    "Update Password",
    "2 Step Security",
    "Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
    "Create Ticket",
    "Subject",
    "Last Reply",
    "Action",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Customer Reply",
    "Upload File",
    "File",
    "Enter Subject",
    "Message",
    "Recent Post",
    "About",
    "Blog",
    "Quick Links",
    "Useful Links",
    "subscribe newsletter",
    "Opps",
    "The page you are looking for was not found",
    "Forbidden",
    "Back To Home",
    "Method Not Allowed",
    "Sorry, your session has expired",
    "Internal Server Error",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator",
    "Enter Email",
    "Shop Now",
    "search",
    "Filter by price",
    "Categories",
    "SHOWING ALL",
    "RESULTS",
    "SORT BY",
    "Latest",
    "Price low to high",
    "Price high to low",
    "Waiting Payment",
    "Payment Processing",
    "Going to Sell",
    "make offer",
    "Make Offer",
    "Description",
    "Post Details",
    "Buy",
    "Payment Completed",
    "Offer History",
    "Accept",
    "Conversation",
    "Reject",
    "Remove",
    "Pending",
    "Accepted",
    "Rejected",
    "Resubmission",
    "Accept Offer",
    "Say Something",
    "Remove Offer",
    "Are you want to remove this offer?",
    "Yes",
    "Reject Offer",
    "Are you want to reject this offer?",
    "Confirmation",
    "Are you confirm to payment now",
    "Make Payment",
    "SELECT PAYMENT OPTION",
    "Buy now",
    "Ask For Help",
    "success",
    "warning",
    "Online",
    "Away",
    "Payment Lock",
    "Type your message",
    "Are you sure to payment lock for",
    "Wallet Balance",
    "Selling Post",
    "Sold Post",
    "Upcoming Payment",
    "Buy Post",
    "My Proposal",
    "Payout Balance",
    "Sell Post",
    "Released At",
    "Released",
    "Upcoming",
    "Last 5 Transactions",
    "danger",
    "Sell Post Create",
    "category",
    "Select Category",
    "Title",
    "How much of this will i earn",
    "Please Enter",
    "credentials",
    "This credentials need for admin approval",
    "Specification",
    "This Specification need for admin approval",
    "Short Comment",
    "Add Image",
    "Submit now",
    "How Much You Earn",
    "You will earn",
    "Sell Charge",
    "Sell Post List",
    "Search for Title",
    "sold",
    "Details",
    "Edit",
    "Delete",
    "Delete Confirm",
    "Are you sure to delete this",
    "Sell Post Edit",
    "preview image",
    "Delete Image",
    "Offer List",
    "My All Post",
    "Type  user or message",
    "Sort By",
    "Latest Offer",
    "ID Purchases",
    "My Offer",
    "Offer Price",
    "Rejected Payment",
    "Complete",
    "Cancel",
    "Transactions",
    "Admin Feedback",
    "Payment Information",
    "Identity Verifiaction",
    "Address Verification",
    "You previous request has been rejected",
    "Identity Type",
    "Select Type",
    "Select",
    "Change",
    "Your KYC submission has been pending",
    "Your KYC already verified",
    "Address Proof",
    "PAYOUT NOW",
    "Pay Out",
    "Next",
    "Transaction Limit:",
    "Charge:",
    "Payout By",
    "Request Amount",
    "Charge Amount",
    "Total Payable",
    "Available Balance",
    "Additional Information To Withdraw Confirm",
    "Confirm Now",
];
